@startmindmap
title 
[ Use Case : 요구사항을 추출해 내는 방법론 ]
end title

* Use Case 
** 배경
*** Software Engineering
**** 반복적 분석과 설계
***** 요구사항 분석
******_ 요구사항 파악
*******_ 모델링
***** 설계
***** 개발
***** 테스트
*** 모델링
**** 현실세계의 단면을 추상화 혹은 일반화 하는 작업
*****_ 특성추출
*****_ Use case
******_ 여러개의 시나리오를 일반화
**** 개발자와 사용자의 의사소통을 가능하게 함
**** 공학적 프로젝트 관리
*****_ 절차와 규칙
***[#Orange] UML
**** Unified Modeling Language
*****_ 표준 모델링 언어
**** 객체지향방법론
**** 구성
***** 시스템을 보는 다양한 관점 View
******[#lightgreen] Class Diagram(클래스 다이어그램)
******[#lightgreen] Object Diagram(객체 다이어 그램)
******[#lightgreen] Use-Case Diagram(쓰임새 다이어 그램)
******[#lightgreen] State Diagram(상태 다이어 그램)
******[#lightgreen] Sequence Diagram(시퀀스 다이어 그램)
****** Activity Diagram(활동 다이어 그램)
****** Collaboration Diagram(협력 다이어 그램)
******[#lightgreen] Component Diagram(컴포넌트 다이어 그램)
****** Deployment Diagram(배치 다이어 그램)
***** 하나의 시스템을 나타내며 상호 변환 가능
** 내용

*** 개요
****_ 유즈케이스는 시스템의 요구사항을 추출해 내는 방법론
****_ 시스템 사용 형태를 모델링
*****_ 각각의 유즈케이스는 하나이상의 시나리오를 제공한다
****_ 유즈케이스는 시스템을 블랙박스와 같이 간주한다
*****_ 기능이 어떻게 구현될지에 대한\n 제약을 두지 않는다

*** 분석방법
**** Bottom-up
***** Problem scenario
******_ 시스템과 사용자간의 구체적인 상호작용에 대한 자세한 기술
******_ 자체로 기능이나 정보를 설명할 수 없다
***** conventional use case
****** 구체적 명칭
*******_ 상징적 명칭
****** 상수
*******_ 변수
****** 사용자 
*******_ 행동
****** 시스템
*******_ 반응
***** essential use case
****** 사용자의 목적이나 의도
*******_ 시스템의 설계및 구현내용
****** 사용자
*******_ 의도
****** 시스템
*******_ 의무
**** Top-down
***** user role model에서 essential use case를 도출
***** 질문
****** 역할을 수행 하면서 
*******_ 달성 하고자 하는 목표?
****** 역항을 수행하기 위해
*******_ 어떤 행위를 수행?
*******_ 어떤 정보나 기능이 필요한가?
*******_ 시스템은 사용자에게 어떤 정보를 얼마나 자주 제공?
*******_ 사용자는 시스템에 어떤 정보를 얼마나 자주 입력?
*** Use case Model
**** Actor
***** 시스템의 일부가 아니다
***** 시스템과 상호작용하는 모든 것
******_ 사용자
******_ 연관된 다른 시스템
***** 정보의 입력과 출력
***** actor 관점에 따라 모델이 만들어 진다
******_ 일반 사용자
******_ 관라자
*** use case
****_ 시스템과 actor와의 의사소통
****_ 시스템 전체의 기능을 나타냄
****_ 하나의 use case는 actor가 원하는 기능을 수행하기 위해\n 시스템이 수행하는 일련의 처리들의 연속
*** relationship
**** actor - use case
***** 엑터와 유즈케이스간의 의사소통
******_ 연관(association) 혹은\n 커뮤니케이션 연관(Communication Association)
***** 방향
******_ 양방향
******_ 단방향
**** Use Case - use case
***** 포함(Inclusion) 혹은 사용(Use)
******_ 회원제를 기반으로 한 인터넷 사이트에 접속하셔서\n 각종 서비스를 제공받기에 앞서\n 늘 수행하는 회원인증과 같은 유즈케이스 
***** 확장(Extension)
****** 특정 조건이나 액터의 선택에 따라\n 발생하는 유즈케이스
*******_ ATM에서 사용자의 메뉴선택에 따라\n 달라지는 유즈케이스의 경우나\n 긴급상황시에 발생할 수 있는 유즈케이스

*** 제약
**** 기능 요구사항을 추출하는데는 도움이 되나\n 비기능적 요구사항을 추출하는데는 적합하지 않다
*****_ Subtopic



@endmindmap

